require 'configs/alpha'
require 'configs/autopairs'
require 'configs/autotag'
require 'configs/bufferline'
require 'configs/cmp'
require 'configs/hop'
require 'configs/indent_blankline'
require 'configs/keybinds'
require 'configs/lspconfig'
require 'configs/lualine'
require 'configs/nvim-tree'
require 'configs/surround'
require 'configs/telescope'
require 'configs/trouble'

